language: scala
scala: "2.9.1"
jdk:
 - oraclejdk6
 - openjdk6
env: PLAY_VERSION=2.0.4
before_script:
 - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
 - unzip -q play-${PLAY_VERSION}.zip 
script: play-${PLAY_VERSION}/play test
notifications:
  email: false
